FROM rancher/hardened-build-base:v1.25.10b1@sha256:92ecda122083602ae6e698244dbc91e7108a37d636486325e00940d8e98ab858 AS builder
WORKDIR /app

COPY . .
RUN go mod download

RUN CGO_ENABLED=0 go build -o proxy ./cmd/proxy

FROM scratch
COPY --from=builder /app/proxy .
CMD ["./proxy"]
