FROM rancher/hardened-build-base:v1.25.12b1@sha256:1b586caca4f7027277aeeab1e9e2831c6760daf8877df8d921081e74763c3021 AS builder
WORKDIR /app

COPY . .
RUN go mod download

RUN CGO_ENABLED=0 go build -o proxy ./cmd/proxy

FROM scratch
COPY --from=builder /app/proxy .
CMD ["./proxy"]
