FROM golang:1.24 AS build

WORKDIR /src

ARG TARGETARCH
ENV GOARCH=${TARGETARCH}

COPY go.mod go.sum .
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o /remotedialer-proxy-client ./examples/proxyclient

FROM scratch

COPY --from=build /remotedialer-proxy-client /

ENTRYPOINT ["/remotedialer-proxy-client"]
