FROM rancher/hardened-build-base:v1.27.1b1@sha256:3c15dacfa0bce49b25e94ec2d8ae7489cfabc6d083f9e421f394da3f8e364e7a AS builder
WORKDIR /app

COPY . .
RUN go mod download

RUN CGO_ENABLED=0 go build -o proxy ./cmd/proxy

FROM scratch
COPY --from=builder /app/proxy .
CMD ["./proxy"]
