apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rdproxy-secret-reader
  namespace: rdproxy-test
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rdproxy-secret-reader-binding
  namespace: rdproxy-test
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: rdproxy-secret-reader
  apiGroup: rbac.authorization.k8s.io
