apiVersion: v1
kind: Service
metadata:
  name: rdproxy
  namespace: rdproxy-test
spec:
  selector:
    app: rdproxy
  ports:
    - name: http
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: proxy
      protocol: TCP
      port: 6666
      targetPort: proxy
  type: ClusterIP
